[build]
  publish = "dist"
  command = "npm run generate -- --no-build --NODE_ENV PRODUCTION"

[context.master]
  publish = "dist"
  command = "npm run incremental-build"
  environment = { NODE_ENV = "PRODUCTION"}